# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

from setuptools import find_packages

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ""

setup(
    long_description=readme,
    name="gptsenpai",
    version="0.1.2",
    python_requires="==3.*,>=3.6.5",
    author="mei",
    author_email="mingzhe-yang@g.ecc.u-tokyo.ac.jp",
    maintainer="kei moriyama",
    maintainer_email="kei-moriyama@g.ecc.u-tokyo.ac.jp",
    license="MIT",
    packages=find_packages(),
    package_dir={"": "."},
    extras_require={
        "dev": [
            "black>=23.3.0",
            "flake8>=6.0.0",
            "isort>=5.12.0",
            "mypy>=1.3.0",
            "pytest>=7.3.1",
            "ipdb>=0.13.13",
            "pre-commit>=3.3.1",
        ]
    },
)
